name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag furkan748/gardiyan:latest
    - name: Push the Docker image
      run: docker push furkan748/gardiyan:latest
      
    - name: Helm Kurulumu
      uses: azure/setup-helm@v4
      with:
        version: 'latest'

    - name: Helm Chart'ı Paketle
      run: helm package ./helm/gardiyan | ls
        
    - name: Login to Docker Hub 
      run: helm registry login docker.io -u "${{ secrets.DOCKERHUB_USERNAME }}"

    - name: Helm Chart'ı Docker Hub'a Push'la
      run: helm push gardiyan-*.tgz oci://docker.io/${{ secrets.DOCKERHUB_USERNAME }}  
