name: Publish Helm Chart
on:
  push:
    branches:
      - master

jobs:
  package-and-push-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu İndir (Checkout)
        uses: actions/checkout@v4
      - name: Helm Kurulumu
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Docker Hub'a Giriş Yap
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | helm registry login docker.io -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Helm Chart'ı Paketle
        run: helm package ./helm/gardiyan | ls

      - name: Helm Chart'ı Docker Hub'a Push'la
        run: helm push gardiyan-*.tgz oci://docker.io/${{ secrets.DOCKERHUB_USERNAME }}
